# Generated by Django 4.1.2 on 2022-10-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='fecha',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='registros',
            name='hora_fin',
            field=models.TimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='registros',
            name='hora_inicio',
            field=models.TimeField(verbose_name='date published'),
        ),
    ]
